theme: jekyll-theme-minimal
title: Karthik Paga's blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://pagakarthik.github.io/kpaga"
twitter_username: karthikpaga
github_username:  pagakarthik

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
syntax_highlighter: rouge
